# These first lines load the all routes defined as @Route() annotations in any
# controller defined inside the src/AppBundle/Controller/ directory. Controllers
# are loaded recursively, so you can separate them into subdirectories.
# If you don't like to add annotations in your applications, you can also define
# the routes in YAML, XML or PHP files.
# See https://symfony.com/doc/current/book/routing.html
app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    # prefix:   /{_locale}
    # requirements:
    #     _locale: '%app_locales%'
    # defaults:
    #     _locale: '%locale%'

# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See https://symfony.com/doc/current/cookbook/templating/render_without_controller.html

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

homepage:
    path: /
    defaults:
        _controller: AppBundle:Homepage:index

handle_comment_form:
    path: /comment
    defaults:
        _controller: AppBundle:News:handleCommentForm

shop:
    path: /cua-hang/
    defaults:
        _controller: AppBundle:Product:list

shop_category:
    path: /cua-hang/{level1}/{page}
    defaults:
        page: 1
        _controller: AppBundle:Product:list
    requirements:
        level1: '[-\w]+'
        page: '\d+'

news_category:
    path: /{level1}/{page}
    defaults:
        page: 1
        _controller: AppBundle:News:list
    requirements:
        level1: '[-\w]+'
        page: '\d+'

list_category:
    path: /{level1}/{level2}/{page}
    defaults:
        page: 1
        _controller: AppBundle:News:list
    requirements:
        level1: '[-\w]+'
        level2: '[-\w]+'
        page: '\d+'

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

settings:
    resource: "@DmishhSettingsBundle/Resources/config/routing.yml"
    prefix: /admin/settings